### ISSUE TITLE
Keep record of IP data in DB

### ISSUE THREAD

**Issue by vnshgrg** [japanrecruitment/TimeBook-API#39]
This is a must have enhancement for getting IP data from IpStacks API.

Background: We need to get information related to the IP address of user for initializing the session. This will help us keep record of all the sessions and possibly help get better understanding of our users' demographic location.

Problem: Current implementation calls IpStacks API every time a user logs in. We have a free cap of 1,000 API requests per month. In order to minimize our API calls and possibly reduce billing, it is a good idea to keep a record of IP information persistent in our system (DB).

Proposal: When we call `getIpData(sourceIp: string)` first we check in our DB if the IP is already stored and data associated to it. If there's the IP record in our DB then just return the data and don't bother calling the IpStacks API. On the other hand, if the IP is not already in our DB then fetch the IP data from IpStacks API, store it in our DB for further use, then return the data so that the next time same IP is called then we can directly retrieve the necessary data from our DB without the need of going to IpStacks. This reduces our COST and network time.

**Comment by susantlalshrestha** [comment]
It seems like the last merge fixes this issue. So i am closing it.
