### ISSUE TITLE
Sends 2 email verification code

### ISSUE THREAD

**Issue by vnshgrg** [japanrecruitment/TimeBook-API#48]
@susantlalshrestha the await syntax does not seem to solve the problem that we faced today. I will also look into it.

**Comment by susantlalshrestha** [comment]
@vnshgrg. I think It's the issue in frontend dai. In the frontend, while registering the user two graphql queries were being called (registerUser and resendVerificationCode). You can see the logs in the browser's console for both of the queries.

**Comment by vnshgrg** [comment]
Okay! I will add suman to this repo too.

**Comment by vnshgrg** [comment]
@susantlalshrestha I have made a quick fix and created a pull request for suman to review. It indeed was a frontend calling `resend verification code` mutation immediately after the `register` mutation.
